# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2


build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - libclang
    - cmake
    - python3-dev
    - python3-setuptools
    - gcc
  commands:
    - pip install pip-tools
    - pip-compile docs/requirements.in
    - pip install -r docs/requirements.txt
    - pip install .
    - python docs/gen_doc.py
    - mkdocs build -d $READTHEDOCS_OUTPUT/html/

mkdocs:
  configuration: mkdocs.yml

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: docs/requirements.txt